global class FutureMethodRecordProcessing
{    
    
    /*public void onBeforeUpdate(){
        processRecords();
    }

    @future
    public static void processRecords()
    {   
         List<User> userList = new List<User>();

        
             User newUser = new User( 
                    CommunityNickname = 'FirstName' + 'LastName',
                    ContactId = '0037F000006QCC6',
                    Department = 'Department',
                    Email = 'Email@test.com',
                    EmailEncodingKey = 'ISO-8859-1',
                    EmployeeNumber= '634353',
                    FirstName = 'FirstName',
                    IsActive = TRUE,     
                    LastName = 'LastName',
                    ReceivesInfoEmails= TRUE,
                    Username = 'Email@gmail.com',
                    UserRoleId = '00E7F000000SO1nUAG'
                    );
userList.add(newUser);
       
    
    
    insert userList;
    }
    
    */
    
    
}